# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/vcaen/data/workspace/lg

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/vcaen/data/workspace/lg

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running interactive CMake command-line interface..."
	/usr/bin/cmake -i .
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: install/local
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: install/strip
.PHONY : install/strip/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/vcaen/data/workspace/lg/CMakeFiles /home/vcaen/data/workspace/lg/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/vcaen/data/workspace/lg/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named lg

# Build rule for target.
lg: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 lg
.PHONY : lg

# fast build rule for target.
lg/fast:
	$(MAKE) -f CMakeFiles/lg.dir/build.make CMakeFiles/lg.dir/build
.PHONY : lg/fast

src/Automate.o: src/Automate.cpp.o
.PHONY : src/Automate.o

# target to build an object file
src/Automate.cpp.o:
	$(MAKE) -f CMakeFiles/lg.dir/build.make CMakeFiles/lg.dir/src/Automate.cpp.o
.PHONY : src/Automate.cpp.o

src/Automate.i: src/Automate.cpp.i
.PHONY : src/Automate.i

# target to preprocess a source file
src/Automate.cpp.i:
	$(MAKE) -f CMakeFiles/lg.dir/build.make CMakeFiles/lg.dir/src/Automate.cpp.i
.PHONY : src/Automate.cpp.i

src/Automate.s: src/Automate.cpp.s
.PHONY : src/Automate.s

# target to generate assembly for a file
src/Automate.cpp.s:
	$(MAKE) -f CMakeFiles/lg.dir/build.make CMakeFiles/lg.dir/src/Automate.cpp.s
.PHONY : src/Automate.cpp.s

src/Etat.o: src/Etat.cpp.o
.PHONY : src/Etat.o

# target to build an object file
src/Etat.cpp.o:
	$(MAKE) -f CMakeFiles/lg.dir/build.make CMakeFiles/lg.dir/src/Etat.cpp.o
.PHONY : src/Etat.cpp.o

src/Etat.i: src/Etat.cpp.i
.PHONY : src/Etat.i

# target to preprocess a source file
src/Etat.cpp.i:
	$(MAKE) -f CMakeFiles/lg.dir/build.make CMakeFiles/lg.dir/src/Etat.cpp.i
.PHONY : src/Etat.cpp.i

src/Etat.s: src/Etat.cpp.s
.PHONY : src/Etat.s

# target to generate assembly for a file
src/Etat.cpp.s:
	$(MAKE) -f CMakeFiles/lg.dir/build.make CMakeFiles/lg.dir/src/Etat.cpp.s
.PHONY : src/Etat.cpp.s

src/Lexer.o: src/Lexer.cpp.o
.PHONY : src/Lexer.o

# target to build an object file
src/Lexer.cpp.o:
	$(MAKE) -f CMakeFiles/lg.dir/build.make CMakeFiles/lg.dir/src/Lexer.cpp.o
.PHONY : src/Lexer.cpp.o

src/Lexer.i: src/Lexer.cpp.i
.PHONY : src/Lexer.i

# target to preprocess a source file
src/Lexer.cpp.i:
	$(MAKE) -f CMakeFiles/lg.dir/build.make CMakeFiles/lg.dir/src/Lexer.cpp.i
.PHONY : src/Lexer.cpp.i

src/Lexer.s: src/Lexer.cpp.s
.PHONY : src/Lexer.s

# target to generate assembly for a file
src/Lexer.cpp.s:
	$(MAKE) -f CMakeFiles/lg.dir/build.make CMakeFiles/lg.dir/src/Lexer.cpp.s
.PHONY : src/Lexer.cpp.s

src/Symbole.o: src/Symbole.cpp.o
.PHONY : src/Symbole.o

# target to build an object file
src/Symbole.cpp.o:
	$(MAKE) -f CMakeFiles/lg.dir/build.make CMakeFiles/lg.dir/src/Symbole.cpp.o
.PHONY : src/Symbole.cpp.o

src/Symbole.i: src/Symbole.cpp.i
.PHONY : src/Symbole.i

# target to preprocess a source file
src/Symbole.cpp.i:
	$(MAKE) -f CMakeFiles/lg.dir/build.make CMakeFiles/lg.dir/src/Symbole.cpp.i
.PHONY : src/Symbole.cpp.i

src/Symbole.s: src/Symbole.cpp.s
.PHONY : src/Symbole.s

# target to generate assembly for a file
src/Symbole.cpp.s:
	$(MAKE) -f CMakeFiles/lg.dir/build.make CMakeFiles/lg.dir/src/Symbole.cpp.s
.PHONY : src/Symbole.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) -f CMakeFiles/lg.dir/build.make CMakeFiles/lg.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) -f CMakeFiles/lg.dir/build.make CMakeFiles/lg.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) -f CMakeFiles/lg.dir/build.make CMakeFiles/lg.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... lg"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... src/Automate.o"
	@echo "... src/Automate.i"
	@echo "... src/Automate.s"
	@echo "... src/Etat.o"
	@echo "... src/Etat.i"
	@echo "... src/Etat.s"
	@echo "... src/Lexer.o"
	@echo "... src/Lexer.i"
	@echo "... src/Lexer.s"
	@echo "... src/Symbole.o"
	@echo "... src/Symbole.i"
	@echo "... src/Symbole.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

